spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 2000
          service-product:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true # 提前加载，项目一启动就连上sentinel控制台
      web-context-unify: false # 不使用统一上下文
#            request-interceptors:
#              - com.yzh.order.interceptor.XTokenRequestInterceptor
#            retryer: feign.retryer.Default

feign:
  sentinel:
    enabled: true
