server:
  port: 8000
spring:
  profiles:
    active: test
  application:
    name: service-order
  cloud:
    nacos:
        server-addr: 127.0.0.1:8848
        config:
          namespace: ${spring.profiles.active:dev}

logging:
  level:
    com.yzh.order.feign: debug



---
spring:
  config:
      import:
        - nacos:common.properties?group=order
        - nacos:database.properties?group=order
      activate:
        on-profile: dev
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
      - nacos:haha.properties?group=order
    activate:
      on-profile: test
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
      - nacos:hehe.properties?group=order
    activate:
      on-profile: prod