spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations: #全局跨域配置
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-headers: '*'
            allowed-methods: '*'

      routes:
        - id: bing-route
          uri: https://cn.bing.com/
          predicates:
            - name: Path
              args:
                patterns: /search
            - name: Query
              args:
                param: q
#            - Vip=user,leifengyang
            - name: Vip #自定义断言工厂完整写法
              args:
                param: user
                value: leifengyang
          order: 10
          metadata:
            hello: world
        - id: order-route
          uri: lb://service-order
          predicates:  #断言
            - name: Path
              args:
                patterns: /api/order/**
                matchTrailingSlash: true
          filters: #过滤器
            - RewritePath=/api/order/?(?<segment>.*), /$\{segment}
            - OnceToken=X-Response-Token, jwt
          order: 1
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters: #过滤器
            - RewritePath=/api/product/?(?<segment>.*), /$\{segment}
          order: 2
      default-filters: #默认过滤器
        - AddResponseHeader=X-Response-Abc, 123